from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol

from cua.artifact.schema import Target


@dataclass
class Observation:
    url: str
    title: str
    frames: list[dict[str, str]]
    aria: str
    dialogs: list[str] = field(default_factory=list)


class Surface(Protocol):
    async def goto(self, url: str) -> None: ...
    async def observe(self) -> Observation: ...
    async def click(self, target: Target, timeout_ms: int = 15000) -> None: ...
    async def fill(self, target: Target, text: str, timeout_ms: int = 15000) -> None: ...
    async def press(self, key: str) -> None: ...
    async def extract(self, target: Target, timeout_ms: int = 15000) -> str: ...
    async def screenshot(self) -> bytes: ...
    async def click_xy(self, x: float, y: float) -> Target | None: ...
    async def type_text(self, text: str) -> None: ...
    async def current_url(self) -> str: ...
    async def page_text(self) -> str: ...
    async def visible_text(self, text: str, timeout_ms: int = 2000) -> bool: ...
    async def url_matches(self, pattern: str) -> bool: ...
    async def close(self) -> None: ...
